{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-wasm-auth.fullname" . }}
  namespace: {{ .Values.istio.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  client_secret: {{ .Values.oidc.clientSecret | default "" | quote }}
  crypto_secret: {{ required "session.cryptoSecret is required" .Values.session.cryptoSecret | quote }}
{{- end }}
