apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ include "keycloak-wasm-auth.fullname" . }}-keycloak
  namespace: {{ .Values.istio.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    - {{ .Values.keycloak.host | quote }}
  location: MESH_EXTERNAL
  resolution: DNS
  ports:
    - number: 443
      name: https
      protocol: HTTPS
